services:
  kafka:
    image: adbgonzalez/kafka:3.9
    container_name: kafka
    hostname: kafka
    # opcional pero recomendado: expón tamén 9093 só se o precisas dende fóra
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
